<a href="https://colab.research.google.com/github/SaiLeela19/AI_ML_Avanthi_Leela/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a = np.full((5,5),1)
a[1:4,-4:-1] = 0
a[2,2]= 9
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
a = np.full((5,5),1)
a[2:5,1: :2] = 0
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]]


In [ ]:
s = np.zeros(10, dtype = "int")
s[4]=1
print(s)

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [ ]:
n = np.random.randint(1,49, size = 10)

print(n)

[ 3 12 36 24 27 27 46 29 36  6]


In [ ]:
a = np.random.randint(0,8, size = 9)
p = a.reshape(3,3)
p

array([[2, 3, 4],
       [5, 4, 0],
       [1, 5, 2]])

TypeError: 'builtin_function_or_method' object is not subscriptable